name: Tag Check

on:
  push:
    tags:
      - '*'

jobs:
  tag_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check if tag already exists
        run: |
          tag_name=$(echo "${GITHUB_REF#refs/tags/}")
          if git rev-parse "$tag_name" >/dev/null 2>&1; then
            echo "Tag $tag_name already exists. Push rejected."
            exit 1
          fi
